/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

// NOTE: THIS FILE WAS AUTOGENERATED

import { runtime } from "../../";

const l = runtime.exports.core;

export const ConsoleCatcher = l.ConsoleCatcher;
export const JavascriptEvaluator = l.JavascriptEvaluator;
export const renderIfHtmlOutput = l.renderIfHtmlOutput;
export const createCellProxy = l.createCellProxy;
export const hookMarkdownItToKaTeX = l.hookMarkdownItToKaTeX;
export const hookMarkDownItToEmojiPlugin = l.hookMarkDownItToEmojiPlugin;
export const hookMarkdownItToCodemirrorHighlighter = l.hookMarkdownItToCodemirrorHighlighter;
export const cellToText = l.cellToText;
export const notebookContentToText = l.notebookContentToText;
export const precompileJavascriptCode = l.precompileJavascriptCode;
export const textToNotebookContent = l.textToNotebookContent;
