/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

// NOTE: THIS FILE WAS AUTOGENERATED

import { runtime } from "../../../";

const l = runtime.exports.templates.icons;

export const StarboardLogo = l.StarboardLogo;
export const AssetsAddedIcon = l.AssetsAddedIcon;
export const DeleteIcon = l.DeleteIcon;
export const BooleanIcon = l.BooleanIcon;
export const ClockIcon = l.ClockIcon;
export const PlayCircleIcon = l.PlayCircleIcon;
export const TextEditIcon = l.TextEditIcon;
export const GearsIcon = l.GearsIcon;
export const LockClosedIcon = l.LockClosedIcon;
