/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

// NOTE: THIS FILE WAS AUTOGENERATED

import { runtime } from "../../";

const l = runtime.exports.elements;

export const StarboardTextEditor = l.StarboardTextEditor;
export const ConsoleOutputElement = l.ConsoleOutputElement;
export const StarboardContentEditor = l.StarboardContentEditor;
