/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

// NOTE: THIS FILE WAS AUTOGENERATED

import { runtime } from "../../";

const l = runtime.exports.libraries;

export const lit = l.lit;
export const litDirectives = l.litDirectives;
export const litDecorators = l.litDecorators;
export const LitElement = l.LitElement;
export const LitHtml = l.LitHtml;
export const MarkdownIt = l.MarkdownIt as any;
export const YAML = l.YAML;
export const Popper = l.Popper;
export const async = l.async;
